
main :
	make ex1
	make ex2
	make ex3
	make ex4
	make ex5
	make ex6

ex1:
	javac ex1.java

ex2:
	javac ex2.java

ex3:
	javac ex3.java

ex4:
	javac ex4.java

ex5:
	javac ex5.java

ex6:
	javac ex6.java


clean:
	rm -f *.class
